// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newCopyWritingCustom(db *gorm.DB, opts ...gen.DOOption) copyWritingCustom {
	_copyWritingCustom := copyWritingCustom{}

	_copyWritingCustom.copyWritingCustomDo.IWithDO = gen.WithDOFunc[ICopyWritingCustomDo](_copyWritingCustom.copyWritingCustomDo.withDO)

	_copyWritingCustom.copyWritingCustomDo.UseDB(db, opts...)
	_copyWritingCustom.copyWritingCustomDo.UseModel(&model.CopyWritingCustom{})

	tableName := _copyWritingCustom.copyWritingCustomDo.TableName()
	_copyWritingCustom.ALL = field.NewAsterisk(tableName)
	_copyWritingCustom.Endpoint = field.NewString(tableName, "endpoint")
	_copyWritingCustom.GuildID = field.NewString(tableName, "guild_id")
	_copyWritingCustom.Content = field.NewField(tableName, "content")

	_copyWritingCustom.fillFieldMap()

	return _copyWritingCustom
}

type copyWritingCustom struct {
	copyWritingCustomDo copyWritingCustomDo

	ALL      field.Asterisk
	Endpoint field.String
	GuildID  field.String
	Content  field.Field

	fieldMap map[string]field.Expr
}

func (c copyWritingCustom) Table(newTableName string) *copyWritingCustom {
	c.copyWritingCustomDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c copyWritingCustom) As(alias string) *copyWritingCustom {
	c.copyWritingCustomDo.DO = *(c.copyWritingCustomDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *copyWritingCustom) updateTableName(table string) *copyWritingCustom {
	c.ALL = field.NewAsterisk(table)
	c.Endpoint = field.NewString(table, "endpoint")
	c.GuildID = field.NewString(table, "guild_id")
	c.Content = field.NewField(table, "content")

	c.fillFieldMap()

	return c
}

func (c *copyWritingCustom) WithContext(ctx context.Context) ICopyWritingCustomDo {
	return c.copyWritingCustomDo.WithContext(ctx)
}

func (c copyWritingCustom) TableName() string { return c.copyWritingCustomDo.TableName() }

func (c copyWritingCustom) Alias() string { return c.copyWritingCustomDo.Alias() }

func (c copyWritingCustom) Columns(cols ...field.Expr) gen.Columns {
	return c.copyWritingCustomDo.Columns(cols...)
}

func (c *copyWritingCustom) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *copyWritingCustom) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["endpoint"] = c.Endpoint
	c.fieldMap["guild_id"] = c.GuildID
	c.fieldMap["content"] = c.Content
}

func (c copyWritingCustom) clone(db *gorm.DB) copyWritingCustom {
	c.copyWritingCustomDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c copyWritingCustom) replaceDB(db *gorm.DB) copyWritingCustom {
	c.copyWritingCustomDo.ReplaceDB(db)
	return c
}

type copyWritingCustomDo struct {
	gen.GenericsDo[ICopyWritingCustomDo, *model.CopyWritingCustom]
}
type ICopyWritingCustomDo interface {
	gen.IGenericsDo[ICopyWritingCustomDo, *model.CopyWritingCustom]
}

func (c *copyWritingCustomDo) withDO(do gen.Dao) ICopyWritingCustomDo {
	_r := &copyWritingCustomDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ICopyWritingCustomDo](c.withDO)
	return _r
}
