// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"github.com/BetaGoRobot/BetaGo-Redefine/internal/infrastructure/db/model"
)

func newCopyWritingGeneral(db *gorm.DB, opts ...gen.DOOption) copyWritingGeneral {
	_copyWritingGeneral := copyWritingGeneral{}

	_copyWritingGeneral.copyWritingGeneralDo.IWithDO = gen.WithDOFunc[ICopyWritingGeneralDo](_copyWritingGeneral.copyWritingGeneralDo.withDO)

	_copyWritingGeneral.copyWritingGeneralDo.UseDB(db, opts...)
	_copyWritingGeneral.copyWritingGeneralDo.UseModel(&model.CopyWritingGeneral{})

	tableName := _copyWritingGeneral.copyWritingGeneralDo.TableName()
	_copyWritingGeneral.ALL = field.NewAsterisk(tableName)
	_copyWritingGeneral.Endpoint = field.NewString(tableName, "endpoint")
	_copyWritingGeneral.Content = field.NewField(tableName, "content")

	_copyWritingGeneral.fillFieldMap()

	return _copyWritingGeneral
}

type copyWritingGeneral struct {
	copyWritingGeneralDo copyWritingGeneralDo

	ALL      field.Asterisk
	Endpoint field.String
	Content  field.Field

	fieldMap map[string]field.Expr
}

func (c copyWritingGeneral) Table(newTableName string) *copyWritingGeneral {
	c.copyWritingGeneralDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c copyWritingGeneral) As(alias string) *copyWritingGeneral {
	c.copyWritingGeneralDo.DO = *(c.copyWritingGeneralDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *copyWritingGeneral) updateTableName(table string) *copyWritingGeneral {
	c.ALL = field.NewAsterisk(table)
	c.Endpoint = field.NewString(table, "endpoint")
	c.Content = field.NewField(table, "content")

	c.fillFieldMap()

	return c
}

func (c *copyWritingGeneral) WithContext(ctx context.Context) ICopyWritingGeneralDo {
	return c.copyWritingGeneralDo.WithContext(ctx)
}

func (c copyWritingGeneral) TableName() string { return c.copyWritingGeneralDo.TableName() }

func (c copyWritingGeneral) Alias() string { return c.copyWritingGeneralDo.Alias() }

func (c copyWritingGeneral) Columns(cols ...field.Expr) gen.Columns {
	return c.copyWritingGeneralDo.Columns(cols...)
}

func (c *copyWritingGeneral) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *copyWritingGeneral) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["endpoint"] = c.Endpoint
	c.fieldMap["content"] = c.Content
}

func (c copyWritingGeneral) clone(db *gorm.DB) copyWritingGeneral {
	c.copyWritingGeneralDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c copyWritingGeneral) replaceDB(db *gorm.DB) copyWritingGeneral {
	c.copyWritingGeneralDo.ReplaceDB(db)
	return c
}

type copyWritingGeneralDo struct {
	gen.GenericsDo[ICopyWritingGeneralDo, *model.CopyWritingGeneral]
}
type ICopyWritingGeneralDo interface {
	gen.IGenericsDo[ICopyWritingGeneralDo, *model.CopyWritingGeneral]
}

func (c *copyWritingGeneralDo) withDO(do gen.Dao) ICopyWritingGeneralDo {
	_r := &copyWritingGeneralDo{}
	_r.DO = *do.(*gen.DO)
	_r.IWithDO = gen.WithDOFunc[ICopyWritingGeneralDo](c.withDO)
	return _r
}
