// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePromptTemplateArg = "prompt_template_args"

// PromptTemplateArg mapped from table <prompt_template_args>
type PromptTemplateArg struct {
	PromptID    int64  `gorm:"column:prompt_id;primaryKey" json:"prompt_id"`
	TemplateStr string `gorm:"column:template_str" json:"template_str"`
	Task        string `gorm:"column:task" json:"task"`
	Constraints string `gorm:"column:constraints" json:"constraints"`
}

// TableName PromptTemplateArg's table name
func (*PromptTemplateArg) TableName() string {
	return TableNamePromptTemplateArg
}
